### ISSUE TITLE
ServiceLocationChannels as pages

### ISSUE THREAD

**Issue by anttileppa** [Metatavu/wordpress-kunta-api-services#15]
As a content manager i would like to have separate pages for each service location channels and links to them in service pages

**Comment by jerelauha** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [(3) PTV sivupohjat asiakaskohtaiseksi](https://trello.com/c/xVzhU3MV/56-3-ptv-sivupohjat-asiakaskohtaiseksi)

**Comment by jerelauha** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [(3) Palvelukanavat omiksi sivuikseen](https://trello.com/c/DCHqEJtE/68-3-palvelukanavat-omiksi-sivuikseen)
